spring:
  grpc:
    server:
      servlet:
        enabled: false
  application:
    name: country_catalog
  graphql:
    path: /graphql
    graphiql:
      enabled: false
  datasource:
    url: 'jdbc:postgresql://localhost:5432/country_catalog'
    username: postgres
    password: secret
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
      schema: country_catalog
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: country_catalog
    locations: classpath:db/migration/country_catalog
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    open-in-view: false

server:
  port: 8282

logging:
  file:
    path: ./logs/country
  level:
    root: INFO
    org.springframework.kafka: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.web.cors: INFO
    org.apache.catalina.filters.RequestDumperFilter: INFO
    org.springframework.boot.autoconfigure: INFO
