spring:
  application:
    name: country_catalog
  datasource:
    url: 'jdbc:postgresql://localhost:5432/country_catalog'
    username: postgres
    password: secret
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1800000  # Увеличено с 1000 до рекомендуемого значения
      auto-commit: true
      schema: country_catalog
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: country_catalog
    locations: classpath:db/migration/country_catalog
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    generate-ddl: true
    open-in-view: false

server:
  port: 8282